apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    component: rabbitmq
  name: rabbitmq-controller
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: taskQueue
        component: rabbitmq
    spec:
      containers:
      - image: andrewkeig/rabbitmq-mqtt-enabled
        name: rabbitmq
        ports:
        - containerPort: 5672
				- containerPort: 1883
				- containerPort: 15672
        resources:
          limits:
            cpu: 100m
