apiVersion: v1
kind: Service
metadata:
  labels:
    name: rabbitmq
  name: rabbitmq-service
spec:
  ports:
  - port: 5672
  - port: 1883
  - port: 15672
  selector:
    app: taskQueue
    component: rabbitmq
